spring.application.name=backend

# ── Server ──────────────────────────────────────────
server.port=8080

# ── Database ────────────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5432/mediqueue
spring.datasource.username=postgres
spring.datasource.password=qwerty123
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA ─────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ── JWT ─────────────────────────────────────────────
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=604800000

# ── Frontend CORS ────────────────────────────────────
app.frontend-url=http://localhost:3000

# ── Actuator ─────────────────────────────────────────
management.endpoints.web.exposure.include=health,info

# ── OAuth2 (we will fill this later) ─────────────────
# spring.security.oauth2.client.registration.google.client-id=PASTE_LATER
# spring.security.oauth2.client.registration.google.client-secret=PASTE_LATER

# ── Logging ─────────────────────────────────────────
logging.level.com.mediqueue=DEBUG
logging.level.org.springframework.security=DEBUG